// GENERATED by scripts/generate-stamp-library.mjs — do not hand-edit.
// Re-run `pnpm gen:stamps` after changing fixtures/stamps/{Terminals-english,Equipment-english}
// or scripts/stamp-discipline-map.csv. See stamp-library.ts (STAMP_LIBRARY
// merges this in) and .claude/plans/stamp-migration-and-draw-from-spec.md.
import type { StampDefinition } from './stamp-library.js';

export const GENERATED_STAMP_LIBRARY: StampDefinition[] = [
  {
    id: 'bath',
    label: 'Bath',
    labelNl: 'Bad',
    discipline: 'plumbing',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 19.08,
    ports: [],
    iconRef: 'D2_Bath.svg',
    source: 'library'
  },
  {
    id: 'eye-wash',
    label: 'Eye Wash',
    labelNl: 'Oogdouche',
    discipline: 'plumbing',
    category: 'terminal',
    nativeWidth: 45.01,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.543657080270353,
        fractionY: 0.921686399004457
      }
    ],
    iconRef: 'D2_Eye_wash.svg',
    source: 'library'
  },
  {
    id: 'floor-drain',
    label: 'Floor Drain',
    labelNl: 'Vloerput',
    discipline: 'plumbing',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 47.96,
    ports: [],
    iconRef: 'D2_Floor_drain.svg',
    source: 'library'
  },
  {
    id: 'pour-out-sink',
    label: 'Pour Out Sink',
    labelNl: 'Uitstortgootsteen',
    discipline: 'plumbing',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 35.86,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D2_Pour_out_sink.svg',
    source: 'library'
  },
  {
    id: 'sewage-connection',
    label: 'Sewage Connection',
    labelNl: 'Riolering Afvoerpunt',
    discipline: 'plumbing',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 48,
    ports: [],
    iconRef: 'D2_Sewage_connection.svg',
    source: 'library'
  },
  {
    id: 'shower-tray',
    label: 'Shower Tray',
    labelNl: 'Douchebak',
    discipline: 'plumbing',
    category: 'terminal',
    nativeWidth: 47.82,
    nativeHeight: 48,
    ports: [],
    iconRef: 'D2_Shower_tray.svg',
    source: 'library'
  },
  {
    id: 'sink',
    label: 'Sink',
    labelNl: 'Wastafel',
    discipline: 'plumbing',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 30.84,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.496632003508881,
        fractionY: 0.188319439565725
      }
    ],
    iconRef: 'D2_Sink.svg',
    source: 'library'
  },
  {
    id: 'storage-pit',
    label: 'Storage Pit',
    labelNl: 'Ontlastput',
    discipline: 'plumbing',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 40.92,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.0839379870426602,
        fractionY: 0.496906547013379
      },
      {
        id: 'c4712792-6e40-4458-8a55-61401efa0432',
        name: 'Port 2',
        fractionX: 0.923613047675259,
        fractionY: 0.500503585369915
      }
    ],
    iconRef: 'D2_Storage_pit.svg',
    source: 'library'
  },
  {
    id: 'tap-point-cold-water',
    label: 'Tap Point Cold Water',
    labelNl: 'Tappunt koud water',
    discipline: 'plumbing',
    category: 'terminal',
    nativeWidth: 22.35,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.505148639890516,
        fractionY: 0.849207132863339
      }
    ],
    iconRef: 'D2_Tap_point_cold_water.svg',
    source: 'library'
  },
  {
    id: 'tap-point-facade-tap',
    label: 'Tap Point Facade Tap',
    labelNl: 'Tappunt gevelkraan',
    discipline: 'plumbing',
    category: 'terminal',
    nativeWidth: 39.27,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.489185578634827,
        fractionY: 0.832069691990556
      }
    ],
    iconRef: 'D2_Tap_point_facade_tap.svg',
    source: 'library'
  },
  {
    id: 'tap-point-hot-cold-water',
    label: 'Tap Point Hot Cold Water',
    labelNl: 'Tappunt warm koud water',
    discipline: 'plumbing',
    category: 'terminal',
    nativeWidth: 41.25,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.293851165631681,
        fractionY: 0.880902174092925
      },
      {
        id: 'a0b12806-5299-4f3a-bf54-ee9f16c8aef0',
        name: 'Port 2',
        fractionX: 0.700173505835904,
        fractionY: 0.87766431134137
      }
    ],
    iconRef: 'D2_Tap_point_hot_cold_water.svg',
    source: 'library'
  },
  {
    id: 'tap-point-hot-water',
    label: 'Tap Point Hot Water',
    labelNl: 'Tappunt warm water',
    discipline: 'plumbing',
    category: 'terminal',
    nativeWidth: 22.35,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.511770796248014,
        fractionY: 0.801893842079968
      }
    ],
    iconRef: 'D2_Tap_point_hot_water.svg',
    source: 'library'
  },
  {
    id: 'toilet-built-in-reservoir',
    label: 'Toilet Built In Reservoir',
    labelNl: 'Toilet Inbouwreservoir',
    discipline: 'plumbing',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 17.35,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.498173309441381,
        fractionY: 0.302199583066304
      },
      {
        id: 'a1f3b8c5-5d61-46d1-a9cc-052e8afbf04a',
        name: 'Port 2',
        fractionX: 0.763652337294062,
        fractionY: 0.284152099769434
      }
    ],
    iconRef: 'D2_Toilet_built_in_reservoir.svg',
    source: 'library'
  },
  {
    id: 'toilet',
    label: 'Toilet',
    labelNl: 'Toilet',
    discipline: 'plumbing',
    category: 'terminal',
    nativeWidth: 32.04,
    nativeHeight: 48,
    ports: [],
    iconRef: 'D2_Toilet.svg',
    source: 'library'
  },
  {
    id: 'urinal',
    label: 'Urinal',
    labelNl: 'Urinoir',
    discipline: 'plumbing',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 43.65,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.719665275269084,
        fractionY: 0.133221482300572
      },
      {
        id: '0f3739f6-2196-44a7-8c67-3a7a88e8a0be',
        name: 'Port 2',
        fractionX: 0.498938815095319,
        fractionY: 0.128740923814139
      }
    ],
    iconRef: 'D2_Urinal.svg',
    source: 'library'
  },
  {
    id: 'water-meter',
    label: 'Water Meter',
    labelNl: 'Watermeter',
    discipline: 'plumbing',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D2_Water_meter.svg',
    source: 'library'
  },
  {
    id: 'air-socket',
    label: 'Air Socket',
    labelNl: 'Rozet',
    discipline: 'heatingAndCooling',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.330990004562233,
        fractionY: 0.328460038986355
      }
    ],
    iconRef: 'D3_Air_socket.svg',
    source: 'library'
  },
  {
    id: 'co2-connection-point',
    label: 'CO2 Connection Point',
    labelNl: 'Aansluitpunt CO2',
    discipline: 'other',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D3_CO2_connection_point.svg',
    source: 'library'
  },
  {
    id: 'compressed-air-connection-point',
    label: 'Compressed Air Connection Point',
    labelNl: 'Aansluitpunt Perslucht',
    discipline: 'other',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D3_Compressed_air_connection_point.svg',
    source: 'library'
  },
  {
    id: 'damper',
    label: 'Damper',
    labelNl: 'Demper',
    discipline: 'heatingAndCooling',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 35.58,
    ports: [],
    iconRef: 'D3_Damper.svg',
    source: 'library'
  },
  {
    id: 'door-slot',
    label: 'Door Slot',
    labelNl: 'Deurspleet',
    discipline: 'heatingAndCooling',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 38.09,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D3_Door_slot.svg',
    source: 'library'
  },
  {
    id: 'flow-arrow-return',
    label: 'Flow Arrow Return',
    labelNl: 'Stromingspijl Retour',
    discipline: 'heatingAndCooling',
    category: 'terminal',
    nativeWidth: 7.48,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D3_Flow_arrow_return.svg',
    source: 'library'
  },
  {
    id: 'flow-arrow-supply',
    label: 'Flow Arrow Supply',
    labelNl: 'Stromingspijl Toevoer',
    discipline: 'heatingAndCooling',
    category: 'terminal',
    nativeWidth: 7.48,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D3_Flow_arrow_supply.svg',
    source: 'library'
  },
  {
    id: 'induction-unit-supply',
    label: 'Induction Unit Supply',
    labelNl: 'Inductieunit Toevoer',
    discipline: 'heatingAndCooling',
    category: 'terminal',
    nativeWidth: 47.28,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.522532560196119,
        fractionY: 0.499168528617877
      },
      {
        id: '959d1287-c919-4348-8cf6-3a79f86cdea8',
        name: 'Port 2',
        fractionX: 0.870889911241229,
        fractionY: 0.464843682498803
      },
      {
        id: 'e54e50bc-d93c-4a17-a08e-deb7565aa840',
        name: 'Port 3',
        fractionX: 0.870889911241229,
        fractionY: 0.490431295060295
      },
      {
        id: 'c28f982d-1192-4058-998a-9f9bd4dec6c9',
        name: 'Port 4',
        fractionX: 0.872702263116316,
        fractionY: 0.514770731399275
      },
      {
        id: '881e7994-a05a-43f6-a29c-f3fd39181279',
        name: 'Port 5',
        fractionX: 0.869681676657837,
        fractionY: 0.537237903404487
      }
    ],
    iconRef: 'D3_Induction_unit_supply.svg',
    source: 'library'
  },
  {
    id: 'linear-grille',
    label: 'Linear Grille',
    labelNl: 'Lijnrooster',
    discipline: 'heatingAndCooling',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 8.78,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.501568470150213,
        fractionY: 0.775839461111439
      }
    ],
    iconRef: 'D3_Linear_grille.svg',
    source: 'library'
  },
  {
    id: 'nozzle',
    label: 'Nozzle',
    labelNl: 'Nozzle',
    discipline: 'heatingAndCooling',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 27.71,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D3_Nozzle.svg',
    source: 'library'
  },
  {
    id: 'radiation-panel',
    label: 'Radiation Panel',
    labelNl: 'Stralingspaneel',
    discipline: 'heatingAndCooling',
    category: 'terminal',
    nativeWidth: 14.56,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.477104924995908,
        fractionY: 0.00911690897373395
      },
      {
        id: 'ff2cfa37-82b7-4b2c-9029-7cbe8fb78633',
        name: 'Port 2',
        fractionX: 0.531599788438776,
        fractionY: 0.00870893262510665
      }
    ],
    iconRef: 'D3_Radiation_panel.svg',
    source: 'library'
  },
  {
    id: 'radiator-type22',
    label: 'Radiator Type22',
    labelNl: 'Radiator Type22',
    discipline: 'heatingAndCooling',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 3.99,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.0417207792207792,
        fractionY: 0.335
      },
      {
        id: '9d01c543-25ac-4e8e-bff5-1992338686a7',
        name: 'Port 2',
        fractionX: 0.0425324675324675,
        fractionY: 0.614761904761905
      }
    ],
    iconRef: 'D3_Radiator_Type22.svg',
    source: 'library'
  },
  {
    id: 'radiator-type33',
    label: 'Radiator Type33',
    labelNl: 'Radiator Type33',
    discipline: 'heatingAndCooling',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 6.07,
    ports: [],
    iconRef: 'D3_Radiator_Type33.svg',
    source: 'library'
  },
  {
    id: 'roof-cap',
    label: 'Roof Cap',
    labelNl: 'Dakkap',
    discipline: 'heatingAndCooling',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 47.94,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D3_Roof_cap.svg',
    source: 'library'
  },
  {
    id: 'underfloor-heating',
    label: 'Underfloor Heating',
    labelNl: 'Vloerverwarming',
    discipline: 'heatingAndCooling',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 34.75,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D3_Underfloor_heating.svg',
    source: 'library'
  },
  {
    id: 'ventilation-grille-rectangular',
    label: 'Ventilation Grille Rectangular',
    labelNl: 'Ventilatierooster Rechthoekig',
    discipline: 'heatingAndCooling',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 47.66,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D3_Ventilation_grille_rectangular.svg',
    source: 'library'
  },
  {
    id: 'ventilation-grille-rh-supply-2',
    label: 'Ventilation Grille Rh Supply 2',
    labelNl: 'Ventilatierooster Rh Toevoer 2',
    discipline: 'heatingAndCooling',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 47.75,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D3_Ventilation_grille_rh_supply_2.svg',
    source: 'library'
  },
  {
    id: 'ventilation-grille-rh-supply',
    label: 'Ventilation Grille Rh Supply',
    labelNl: 'Ventilatierooster Rh Toevoer',
    discipline: 'heatingAndCooling',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 47.75,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.49856353181386,
        fractionY: 0.576274925812745
      }
    ],
    iconRef: 'D3_Ventilation_grille_rh_supply.svg',
    source: 'library'
  },
  {
    id: 'ventilation-grille-round-supply',
    label: 'Ventilation Grille Round Supply',
    labelNl: 'Ventilatierooster Rond Toevoer',
    discipline: 'heatingAndCooling',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 47.75,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D3_Ventilation_grille_round_supply.svg',
    source: 'library'
  },
  {
    id: 'ventilation-grille-round',
    label: 'Ventilation Grille Round',
    labelNl: 'Ventilatierooster',
    discipline: 'heatingAndCooling',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.500970229136369,
        fractionY: 0.913860940409585
      }
    ],
    iconRef: 'D3_Ventilation_grille_round.svg',
    source: 'library'
  },
  {
    id: 'wall-grille-plenum',
    label: 'Wall Grille Plenum',
    labelNl: 'Wandrooster Plenum',
    discipline: 'heatingAndCooling',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 16.05,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.501715308180705,
        fractionY: 0.899255453422567
      }
    ],
    iconRef: 'D3_Wall_grille_plenum.svg',
    source: 'library'
  },
  {
    id: 'wall-grille',
    label: 'Wall Grille',
    labelNl: 'Wandrooster',
    discipline: 'heatingAndCooling',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 9.05,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D3_Wall_grille.svg',
    source: 'library'
  },
  {
    id: 'dry-riser-facade-cabinet',
    label: 'Dry Riser Facade Cabinet',
    labelNl: 'Droge Blusleiding Gevelkast',
    discipline: 'fireProtection',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 44.28,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D4_Dry_riser_facade_cabinet.svg',
    source: 'library'
  },
  {
    id: 'dry-riser-fire-hydrant',
    label: 'Dry Riser Fire Hydrant',
    labelNl: 'Droge Blusleiding Brandkraan',
    discipline: 'fireProtection',
    category: 'terminal',
    nativeWidth: 30.13,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D4_Dry_riser_fire_hydrant.svg',
    source: 'library'
  },
  {
    id: 'fire-hose-reel-cabinet',
    label: 'Fire Hose Reel Cabinet',
    labelNl: 'Brandslanghaspelkast',
    discipline: 'fireProtection',
    category: 'terminal',
    nativeWidth: 20.51,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.50182579482935,
        fractionY: 0.856847742083251
      }
    ],
    iconRef: 'D4_Fire_hose_reel_cabinet.svg',
    source: 'library'
  },
  {
    id: 'nitrogen-connection-point',
    label: 'Nitrogen Connection Point',
    labelNl: 'Aansluitpunt Stikstof',
    discipline: 'other',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D4_Nitrogen_connection_point.svg',
    source: 'library'
  },
  {
    id: 'oxygen-connection-point',
    label: 'Oxygen Connection Point',
    labelNl: 'Aansluitpunt Zuurstof',
    discipline: 'other',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D4_Oxygen_connection_point.svg',
    source: 'library'
  },
  {
    id: 'sprinkler-head',
    label: 'Sprinkler Head',
    labelNl: 'Sprinklerkop',
    discipline: 'other',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D4_Sprinkler_head.svg',
    source: 'library'
  },
  {
    id: 'vacuum-connection-point',
    label: 'Vacuum Connection Point',
    labelNl: 'Aansluitpunt Vacuum',
    discipline: 'other',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D4_Vacuum_connection_point.svg',
    source: 'library'
  },
  {
    id: 'connection-point-400v-3fpe',
    label: 'Connection Point 400V 3FPE',
    labelNl: 'Aansluitpunt 400V 3FPE',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 22.83,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Connection_point_400V_3FPE.svg',
    source: 'library'
  },
  {
    id: 'connection-point-sun-screen',
    label: 'Connection Point Sun Screen',
    labelNl: 'Aansluitpunt Zonwering',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 18.42,
    nativeHeight: 48,
    ports: [],
    iconRef: 'D5_Connection_point_Sun_Screen.svg',
    source: 'library'
  },
  {
    id: 'connection-point',
    label: 'Connection Point',
    labelNl: 'Aansluitpunt',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 23.48,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Connection_point.svg',
    source: 'library'
  },
  {
    id: 'earthing-central-earthing-connection',
    label: 'Earthing Central Earthing Connection',
    labelNl: 'Aarding CAP',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 27.38,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Earthing_central_earthing_connection.svg',
    source: 'library'
  },
  {
    id: 'earthing-equipotential-bonding',
    label: 'Earthing Equipotential Bonding',
    labelNl: 'Aarding Potentiaalvereffening',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 25.79,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Earthing_equipotential_bonding.svg',
    source: 'library'
  },
  {
    id: 'earthing-rod',
    label: 'Earthing Rod',
    labelNl: 'Aardpen',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 22.35,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Earthing_rod.svg',
    source: 'library'
  },
  {
    id: 'escape-route-down',
    label: 'Escape Route Down',
    labelNl: 'Vluchtroute Omlaag',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 24.81,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Escape_route_down.svg',
    source: 'library'
  },
  {
    id: 'escape-route-left',
    label: 'Escape Route Left',
    labelNl: 'Vluchtroute Links',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 24.81,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Escape_route_left.svg',
    source: 'library'
  },
  {
    id: 'escape-route-right',
    label: 'Escape Route Right',
    labelNl: 'Vluchtroute Rechts',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 24.81,
    ports: [],
    iconRef: 'D5_Escape_route_right.svg',
    source: 'library'
  },
  {
    id: 'escape-route-stair-down-left',
    label: 'Escape Route Stair Down Left',
    labelNl: 'Vluchtroute Trap Neer Links',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 24.81,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Escape_route_stair_down_left.svg',
    source: 'library'
  },
  {
    id: 'escape-route-stair-down-right',
    label: 'Escape Route Stair Down Right',
    labelNl: 'Vluchtroute Trap Neer Rechts',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 24.81,
    ports: [],
    iconRef: 'D5_Escape_route_stair_down_right.svg',
    source: 'library'
  },
  {
    id: 'escape-route-stair-left',
    label: 'Escape Route Stair Left',
    labelNl: 'Vluchtroute Trap Op Links',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 24.81,
    ports: [],
    iconRef: 'D5_Escape_route_stair_left.svg',
    source: 'library'
  },
  {
    id: 'escape-route-stair-right',
    label: 'Escape Route Stair Right',
    labelNl: 'Vluchtroute Trap Op Rechts',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 24.81,
    ports: [],
    iconRef: 'D5_Escape_route_stair_right.svg',
    source: 'library'
  },
  {
    id: 'escape-route-up',
    label: 'Escape Route Up',
    labelNl: 'Vluchtroute Omhoog',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 24.81,
    ports: [],
    iconRef: 'D5_Escape_route_up.svg',
    source: 'library'
  },
  {
    id: 'grounding-mat',
    label: 'Grounding Mat',
    labelNl: 'Aardingsmat',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 47.83,
    ports: [],
    iconRef: 'D5_Grounding_mat.svg',
    source: 'library'
  },
  {
    id: 'junction-box',
    label: 'Junction Box',
    labelNl: 'Centraaldoos',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 47.83,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Junction_box.svg',
    source: 'library'
  },
  {
    id: 'key-locker',
    label: 'Key Locker',
    labelNl: 'Sleutelbuis',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Key_locker.svg',
    source: 'library'
  },
  {
    id: 'kilowatt-meter',
    label: 'Kilowatt Meter',
    labelNl: 'Kilowatuurmeter',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 20.09,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Kilowatt_meter.svg',
    source: 'library'
  },
  {
    id: 'luminaire-rectangular-emergency',
    label: 'Luminaire Rectangular Emergency',
    labelNl: 'Armatuur Rechthoekig Nood',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 13.49,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Luminaire_rectangular_emergency.svg',
    source: 'library'
  },
  {
    id: 'luminaire-rectangular-waterproof',
    label: 'Luminaire Rectangular Waterproof',
    labelNl: 'Armatuur Rechthoekig Waterdicht',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 13.49,
    ports: [],
    iconRef: 'D5_Luminaire_rectangular_waterproof.svg',
    source: 'library'
  },
  {
    id: 'luminaire-rectangular',
    label: 'Luminaire Rectangular',
    labelNl: 'Armatuur Rechthoekig',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 13.49,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Luminaire_rectangular.svg',
    source: 'library'
  },
  {
    id: 'luminaire-rh-wall',
    label: 'Luminaire Rh Wall',
    labelNl: 'Armatuur Rh Wand',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 43.64,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Luminaire_rh_wall.svg',
    source: 'library'
  },
  {
    id: 'luminaire-rh2-wall',
    label: 'Luminaire Rh2 Wall',
    labelNl: 'Armatuur Rh2 Wand',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 19.8,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Luminaire_rh2_wall.svg',
    source: 'library'
  },
  {
    id: 'luminaire-round-emergency',
    label: 'Luminaire Round Emergency',
    labelNl: 'Armatuur Rond Nood',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 42.97,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Luminaire_round_emergency.svg',
    source: 'library'
  },
  {
    id: 'luminaire-round-wall-emergency',
    label: 'Luminaire Round Wall Emergency',
    labelNl: 'Armatuur Rond Wand Nood',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 44.55,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Luminaire_round_wall_emergency.svg',
    source: 'library'
  },
  {
    id: 'luminaire-round-wall-waterproof',
    label: 'Luminaire Round Wall Waterproof',
    labelNl: 'Armatuur Rond Wand Waterdicht',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 44.55,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Luminaire_round_wall_waterproof.svg',
    source: 'library'
  },
  {
    id: 'luminaire-round-wall',
    label: 'Luminaire Round Wall',
    labelNl: 'Armatuur Rond Wand',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 44.76,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Luminaire_round_wall.svg',
    source: 'library'
  },
  {
    id: 'luminaire-round-waterproof',
    label: 'Luminaire Round Waterproof',
    labelNl: 'Armatuur Rond Waterdicht',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 42.97,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Luminaire_round_waterproof.svg',
    source: 'library'
  },
  {
    id: 'luminaire-round',
    label: 'Luminaire Round',
    labelNl: 'Armatuur Rond',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 42.97,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.427471670120425,
        fractionY: 0.502317945676633
      }
    ],
    iconRef: 'D5_Luminaire_round.svg',
    source: 'library'
  },
  {
    id: 'luminaire-spot-emergency',
    label: 'Luminaire Spot Emergency',
    labelNl: 'Armatuur Spot Nood',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Luminaire_spot_emergency.svg',
    source: 'library'
  },
  {
    id: 'luminaire-spot-waterproof',
    label: 'Luminaire Spot Waterproof',
    labelNl: 'Armatuur Spot Waterdicht',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Luminaire_spot_waterproof.svg',
    source: 'library'
  },
  {
    id: 'luminaire-spot',
    label: 'Luminaire Spot',
    labelNl: 'Armatuur Spot',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Luminaire_spot.svg',
    source: 'library'
  },
  {
    id: 'luto',
    label: 'LUTO',
    labelNl: 'LUTO',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 17.91,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_LUTO.svg',
    source: 'library'
  },
  {
    id: 'motion-sensor-wall',
    label: 'Motion Sensor Wall',
    labelNl: 'Bewegingsensor Wand',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 22.36,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Motion_sensor_wall.svg',
    source: 'library'
  },
  {
    id: 'motion-sensor',
    label: 'Motion Sensor',
    labelNl: 'Bewegingsensor',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 44.56,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Motion_sensor.svg',
    source: 'library'
  },
  {
    id: 'signal-lamp',
    label: 'Signal Lamp',
    labelNl: 'Signaallamp',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Signal_lamp.svg',
    source: 'library'
  },
  {
    id: 'solar-panel',
    label: 'Solar Panel',
    labelNl: 'PV Paneel',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 22.18,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Solar_panel.svg',
    source: 'library'
  },
  {
    id: 'switch-changeover',
    label: 'Switch Changeover',
    labelNl: 'Schakelaar Wissel',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 39.23,
    nativeHeight: 48,
    ports: [],
    iconRef: 'D5_Switch_changeover.svg',
    source: 'library'
  },
  {
    id: 'switch-dimmer',
    label: 'Switch Dimmer',
    labelNl: 'Schakelaar Dimmer',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 40.77,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Switch_dimmer.svg',
    source: 'library'
  },
  {
    id: 'switch-double',
    label: 'Switch Double',
    labelNl: 'Schakelaar 2voudig',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 40.77,
    nativeHeight: 48,
    ports: [],
    iconRef: 'D5_Switch_double.svg',
    source: 'library'
  },
  {
    id: 'switch-elbow',
    label: 'Switch Elbow',
    labelNl: 'Schakelaar Elleboog',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 46.23,
    nativeHeight: 48,
    ports: [],
    iconRef: 'D5_Switch_elbow.svg',
    source: 'library'
  },
  {
    id: 'switch-emergency',
    label: 'Switch Emergency',
    labelNl: 'Noodschakelaar',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Switch_emergency.svg',
    source: 'library'
  },
  {
    id: 'switch-pull-cord',
    label: 'Switch Pull Cord',
    labelNl: 'Schakelaar Trekkoord',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 40.77,
    nativeHeight: 48,
    ports: [],
    iconRef: 'D5_Switch_pull_cord.svg',
    source: 'library'
  },
  {
    id: 'switch-pulse',
    label: 'Switch Pulse',
    labelNl: 'Schakelaar Pulsdrukker',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 48,
    ports: [],
    iconRef: 'D5_Switch_pulse.svg',
    source: 'library'
  },
  {
    id: 'switch-socket-combo-changeover',
    label: 'Switch Socket Combo Changeover',
    labelNl: 'Schakelaar Wcd Combi Wissel',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 33.5,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Switch_socket_combo_changeover.svg',
    source: 'library'
  },
  {
    id: 'switch-socket-combo',
    label: 'Switch Socket Combo',
    labelNl: 'Schakelaar Wcd Combi',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 33.72,
    nativeHeight: 48,
    ports: [],
    iconRef: 'D5_Switch_socket_combo.svg',
    source: 'library'
  },
  {
    id: 'switch-up-down',
    label: 'Switch Up Down',
    labelNl: 'Schakelaar Op Neer',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 46.66,
    nativeHeight: 48,
    ports: [],
    iconRef: 'D5_Switch_up_down.svg',
    source: 'library'
  },
  {
    id: 'switch',
    label: 'Switch',
    labelNl: 'Schakelaar',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 40.77,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Switch.svg',
    source: 'library'
  },
  {
    id: 'wall-socket-230v',
    label: 'Wall Socket 230V',
    labelNl: 'Wandcontactdoos 230V',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 25.32,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Wall_socket_230V.svg',
    source: 'library'
  },
  {
    id: 'wall-socket-400v-3fpe',
    label: 'Wall Socket 400V 3FPE',
    labelNl: 'Wandcontactdoos 400V 3FPE',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 21.99,
    nativeHeight: 48,
    ports: [],
    iconRef: 'D5_Wall_socket_400V_3FPE.svg',
    source: 'library'
  },
  {
    id: 'wall-socket-double-usb',
    label: 'Wall Socket Double USB',
    labelNl: 'Wandcontactdoos 2voudig USB',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 18.8,
    nativeHeight: 48,
    ports: [],
    iconRef: 'D5_Wall_socket_double_USB.svg',
    source: 'library'
  },
  {
    id: 'wall-socket-double',
    label: 'Wall Socket Double',
    labelNl: 'Wandcontactdoos 2voudig',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 22.93,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Wall_socket_double.svg',
    source: 'library'
  },
  {
    id: 'wall-socket-perilex',
    label: 'Wall Socket Perilex',
    labelNl: 'Wandcontactdoos Perilex',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 21.99,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.639911731417894,
        fractionY: 0.877438463008321
      }
    ],
    iconRef: 'D5_Wall_socket_perilex.svg',
    source: 'library'
  },
  {
    id: 'wall-socket-quadruple',
    label: 'Wall Socket Quadruple',
    labelNl: 'Wandcontactdoos 4voudig',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 16.39,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Wall_socket_quadruple.svg',
    source: 'library'
  },
  {
    id: 'wall-socket-triple',
    label: 'Wall Socket Triple',
    labelNl: 'Wandcontactdoos 3voudig',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 19.12,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Wall_socket_triple.svg',
    source: 'library'
  },
  {
    id: 'wall-socket-usb',
    label: 'Wall Socket USB',
    labelNl: 'Wandcontactdoos USB',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 22.93,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Wall_socket_USB.svg',
    source: 'library'
  },
  {
    id: 'wall-socket',
    label: 'Wall Socket',
    labelNl: 'Wandcontactdoos',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 22.93,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Wall_socket.svg',
    source: 'library'
  },
  {
    id: 'wireless-charger',
    label: 'Wireless Charger',
    labelNl: 'Draadloze Oplader',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Wireless_charger.svg',
    source: 'library'
  },
  {
    id: 'intercom',
    label: 'Intercom',
    labelNl: 'Intercom',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 40.65,
    ports: [],
    iconRef: 'D6_Intercom.svg',
    source: 'library'
  },
  {
    id: 'speaker',
    label: 'Speaker',
    labelNl: 'Speaker',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 29.8,
    ports: [],
    iconRef: 'D6_Speaker.svg',
    source: 'library'
  },
  {
    id: 'video-intercom',
    label: 'Video Intercom',
    labelNl: 'Intercom Video',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 29.46,
    nativeHeight: 48,
    ports: [],
    iconRef: 'D6_Video_intercom.svg',
    source: 'library'
  },
  {
    id: 'burglar-alarm-central',
    label: 'Burglar Alarm Central',
    labelNl: 'Inbraakcentrale',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 25.59,
    ports: [],
    iconRef: 'D7_Burglar_alarm_central.svg',
    source: 'library'
  },
  {
    id: 'camera-dome',
    label: 'Camera Dome',
    labelNl: 'Camera Dome',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 24.02,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D7_Camera_dome.svg',
    source: 'library'
  },
  {
    id: 'camera-movable',
    label: 'Camera Movable',
    labelNl: 'Camera Beweegbaar',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 20.93,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D7_Camera_movable.svg',
    source: 'library'
  },
  {
    id: 'camera',
    label: 'Camera',
    labelNl: 'Camera',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 16.79,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D7_Camera.svg',
    source: 'library'
  },
  {
    id: 'card-reader',
    label: 'Card Reader',
    labelNl: 'Kaartlezer',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 34.05,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D7_Card_reader.svg',
    source: 'library'
  },
  {
    id: 'code-control-panel',
    label: 'Code Control Panel',
    labelNl: 'Codebedienpaneel',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 36.23,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D7_Code_control_panel.svg',
    source: 'library'
  },
  {
    id: 'data-point-double',
    label: 'Data Point Double',
    labelNl: 'Datapunt 2voudig',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 22.18,
    nativeHeight: 48,
    ports: [],
    iconRef: 'D7_Data_point_double.svg',
    source: 'library'
  },
  {
    id: 'data-point-quadruple',
    label: 'Data Point Quadruple',
    labelNl: 'Datapunt 4voudig',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 22.18,
    nativeHeight: 48,
    ports: [],
    iconRef: 'D7_Data_point_quadruple.svg',
    source: 'library'
  },
  {
    id: 'data-point-triple',
    label: 'Data Point Triple',
    labelNl: 'Datapunt 3voudig',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 21.45,
    nativeHeight: 48,
    ports: [],
    iconRef: 'D7_Data_point_triple.svg',
    source: 'library'
  },
  {
    id: 'data-point',
    label: 'Data Point',
    labelNl: 'Datapunt',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 22.18,
    nativeHeight: 48,
    ports: [],
    iconRef: 'D7_Data_point.svg',
    source: 'library'
  },
  {
    id: 'display-screen',
    label: 'Display Screen',
    labelNl: 'Beeldscherm',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 24.33,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D7_Display_screen.svg',
    source: 'library'
  },
  {
    id: 'door-holder-magnet',
    label: 'Door Holder Magnet',
    labelNl: 'Kleefmagneet',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 29.86,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      },
      {
        id: 'bad2c6b7-0392-4bfe-8d3d-9fa57beb0282',
        name: 'Port 2',
        fractionX: 0,
        fractionY: 0
      }
    ],
    iconRef: 'D7_Door_holder_magnet.svg',
    source: 'library'
  },
  {
    id: 'door-signaling',
    label: 'Door Signaling',
    labelNl: 'Deursignalering',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 16.35,
    ports: [],
    iconRef: 'D7_Door_signaling.svg',
    source: 'library'
  },
  {
    id: 'doorbell',
    label: 'Doorbell',
    labelNl: 'Beldrukker',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 48,
    ports: [],
    iconRef: 'D7_Doorbell.svg',
    source: 'library'
  },
  {
    id: 'evacuation-speaker',
    label: 'Evacuation Speaker',
    labelNl: 'Speaker Ontruiming',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 29.97,
    ports: [],
    iconRef: 'D7_Evacuation_speaker.svg',
    source: 'library'
  },
  {
    id: 'interlock-lights',
    label: 'Interlock Lights',
    labelNl: 'Interlocklampen',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 21.98,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D7_Interlock_lights.svg',
    source: 'library'
  },
  {
    id: 'key-safe',
    label: 'Key Safe',
    labelNl: 'Sleutelkluis',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 15.9,
    nativeHeight: 48,
    ports: [],
    iconRef: 'D7_Key_safe.svg',
    source: 'library'
  },
  {
    id: 'manual-fire-alarm',
    label: 'Manual Fire Alarm',
    labelNl: 'Handbrandmelder',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 44.31,
    nativeHeight: 48,
    ports: [],
    iconRef: 'D7_Manual_fire_alarm.svg',
    source: 'library'
  },
  {
    id: 'motion-detector-90-degrees',
    label: 'Motion Detector 90 Degrees',
    labelNl: 'Sensor PIR 90 Graden',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 33.65,
    nativeHeight: 48,
    ports: [],
    iconRef: 'D7_Motion_detector_90_degrees.svg',
    source: 'library'
  },
  {
    id: 'multi-detector',
    label: 'Multi Detector',
    labelNl: 'Multimelder',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 48,
    ports: [],
    iconRef: 'D7_Multi_detector.svg',
    source: 'library'
  },
  {
    id: 'optical-detector-alternative',
    label: 'Optical Detector Alternative',
    labelNl: 'Optische Melder Alternatief',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 24.21,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D7_Optical_detector_alternative.svg',
    source: 'library'
  },
  {
    id: 'optical-detector',
    label: 'Optical Detector',
    labelNl: 'Optische Melder',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 48,
    ports: [],
    iconRef: 'D7_Optical_detector.svg',
    source: 'library'
  },
  {
    id: 'remote-indicator',
    label: 'Remote Indicator',
    labelNl: 'Nevenindicator',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D7_Remote_indicator.svg',
    source: 'library'
  },
  {
    id: 'security-alarm',
    label: 'Security Alarm',
    labelNl: 'Sirene Inbraak',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 45.62,
    ports: [],
    iconRef: 'D7_Security_alarm.svg',
    source: 'library'
  },
  {
    id: 'security-beacon-light',
    label: 'Security Beacon Light',
    labelNl: 'Alarmlicht Zwaai',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 48,
    ports: [],
    iconRef: 'D7_Security_Beacon_light.svg',
    source: 'library'
  },
  {
    id: 'security-flash-light',
    label: 'Security Flash Light',
    labelNl: 'Alarmlicht Flits',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 36.1,
    ports: [],
    iconRef: 'D7_Security_Flash_light.svg',
    source: 'library'
  },
  {
    id: 'security-sensor-long-beam',
    label: 'Security Sensor Long Beam',
    labelNl: 'Sensor Long Beam',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 31.82,
    nativeHeight: 48,
    ports: [],
    iconRef: 'D7_Security_sensor_long_beam.svg',
    source: 'library'
  },
  {
    id: 'security-sensor-pir-360',
    label: 'Security Sensor PIR 360',
    labelNl: 'Sensor PIR 360 Graden',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 47.96,
    ports: [],
    iconRef: 'D7_Security_sensor_PIR_360.svg',
    source: 'library'
  },
  {
    id: 'thermal-detector',
    label: 'Thermal Detector',
    labelNl: 'Thermische Melder',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D7_Thermal_detector.svg',
    source: 'library'
  },
  {
    id: 'thermo-optical-detector',
    label: 'Thermo Optical Detector',
    labelNl: 'Thermo Optische Melder',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 48,
    ports: [],
    iconRef: 'D7_Thermo_optical_detector.svg',
    source: 'library'
  },
  {
    id: 'wired-connection-point',
    label: 'Wired Connection Point',
    labelNl: 'Aansluitpunt Bedraad',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 10.47,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D7_Wired_connection_point.svg',
    source: 'library'
  },
  {
    id: 'wireless-connection-point',
    label: 'Wireless Connection Point',
    labelNl: 'Aansluitpunt Onbedraad',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 11.7,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D7_Wireless_connection_point.svg',
    source: 'library'
  },
  {
    id: 'co-lpg-detector',
    label: 'CO LPG Detector',
    labelNl: 'CO LPG Detector',
    discipline: 'electrical',
    category: 'terminal',
    nativeWidth: 29.59,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D8_CO_LPG_detector.svg',
    source: 'library'
  },
  {
    id: 'temperature-sensor',
    label: 'Temperature Sensor',
    labelNl: 'Opnemer Temperatuur',
    discipline: 'heatingAndCooling',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D8_Temperature_sensor.svg',
    source: 'library'
  },
  {
    id: 'thermostat-1',
    label: 'Thermostat 1',
    labelNl: 'Thermostaat 1',
    discipline: 'heatingAndCooling',
    category: 'terminal',
    nativeWidth: 40.14,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D8_Thermostat_1.svg',
    source: 'library'
  },
  {
    id: 'thermostat-2',
    label: 'Thermostat 2',
    labelNl: 'Thermostaat 2',
    discipline: 'heatingAndCooling',
    category: 'terminal',
    nativeWidth: 48,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D8_Thermostat_2.svg',
    source: 'library'
  },
  {
    id: 'air-handling-unit',
    label: 'Air Handling Unit',
    labelNl: 'Luchtbehandelingskast Warmtewiel',
    discipline: 'heatingAndCooling',
    category: 'equipment',
    nativeWidth: 48,
    nativeHeight: 26.15,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.860068210375157,
        fractionY: 0.331083780638213
      },
      {
        id: '368b0064-b64b-4a05-8014-9308aef6d76d',
        name: 'Port 2',
        fractionX: 0.860820956450745,
        fractionY: 0.639171995860724
      },
      {
        id: 'caa4f859-a126-4c35-9211-b095d445119c',
        name: 'Port 3',
        fractionX: 0.0997946740319975,
        fractionY: 0.637558968555894
      },
      {
        id: 'd31f4145-6806-4f0e-805d-5a32cf620250',
        name: 'Port 4',
        fractionX: 0.100547420107585,
        fractionY: 0.319792589504404
      },
      {
        id: '25c44b66-4856-4af8-8116-2005bc8a964c',
        name: 'Port 5',
        fractionX: 0.549936827233195,
        fractionY: 0.119777203705496
      },
      {
        id: '3ee3a6c0-0ce8-4dac-8001-eacf5802bc94',
        name: 'Port 6',
        fractionX: 0.594348845692845,
        fractionY: 0.121390231010326
      }
    ],
    iconRef: 'D3_Air_handling_unit.svg',
    source: 'library'
  },
  {
    id: 'boiler',
    label: 'Boiler',
    labelNl: 'Boiler',
    discipline: 'plumbing',
    category: 'equipment',
    nativeWidth: 48,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D3_Boiler.svg',
    source: 'library'
  },
  {
    id: 'drycooler-section',
    label: 'Drycooler Section',
    labelNl: 'Drycooler Sectie',
    discipline: 'heatingAndCooling',
    category: 'equipment',
    nativeWidth: 33.4,
    nativeHeight: 48,
    ports: [],
    iconRef: 'D3_Drycooler_section.svg',
    source: 'library'
  },
  {
    id: 'drycooler',
    label: 'Drycooler',
    labelNl: 'Drycooler',
    discipline: 'heatingAndCooling',
    category: 'equipment',
    nativeWidth: 16.04,
    nativeHeight: 48,
    ports: [],
    iconRef: 'D3_Drycooler.svg',
    source: 'library'
  },
  {
    id: 'fan-axial',
    label: 'Fan Axial',
    labelNl: 'Ventilator Axiaal',
    discipline: 'heatingAndCooling',
    category: 'equipment',
    nativeWidth: 38.68,
    nativeHeight: 48,
    ports: [],
    iconRef: 'D3_Fan_axial.svg',
    source: 'library'
  },
  {
    id: 'fan-booster',
    label: 'Fan Booster',
    labelNl: 'Ventilator Stuwdruk',
    discipline: 'heatingAndCooling',
    category: 'equipment',
    nativeWidth: 29.26,
    nativeHeight: 48,
    ports: [],
    iconRef: 'D3_Fan_booster.svg',
    source: 'library'
  },
  {
    id: 'fan-coil-unit',
    label: 'Fan Coil Unit',
    labelNl: 'Fan Coil Unit',
    discipline: 'heatingAndCooling',
    category: 'equipment',
    nativeWidth: 48,
    nativeHeight: 21.39,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.0982111172182031,
        fractionY: 0.548665270288337
      },
      {
        id: '69a50c1e-788a-4f46-b023-a50a8925e51d',
        name: 'Port 2',
        fractionX: 0.901788882781797,
        fractionY: 0.641085143001449
      },
      {
        id: '4e3616c2-5356-4917-a8b6-5f3016324988',
        name: 'Port 3',
        fractionX: 0.902861750292563,
        fractionY: 0.441071985637251
      }
    ],
    iconRef: 'D3_Fan_coil_unit.svg',
    source: 'library'
  },
  {
    id: 'fan-exhaust',
    label: 'Fan Exhaust',
    labelNl: 'Ventilator Afblaas',
    discipline: 'heatingAndCooling',
    category: 'equipment',
    nativeWidth: 48,
    nativeHeight: 48,
    ports: [],
    iconRef: 'D3_Fan_exhaust.svg',
    source: 'library'
  },
  {
    id: 'fan',
    label: 'Fan',
    labelNl: 'Ventilator',
    discipline: 'heatingAndCooling',
    category: 'equipment',
    nativeWidth: 48,
    nativeHeight: 45.63,
    ports: [],
    iconRef: 'D3_Fan.svg',
    source: 'library'
  },
  {
    id: 'hrv-unit',
    label: 'HRV Unit',
    labelNl: 'WTW Unit',
    discipline: 'heatingAndCooling',
    category: 'equipment',
    nativeWidth: 48,
    nativeHeight: 48,
    ports: [],
    iconRef: 'D3_HRV_unit.svg',
    source: 'library'
  },
  {
    id: 'distribution-panel',
    label: 'Distribution Panel',
    labelNl: 'Verdeelinrichting',
    discipline: 'electrical',
    category: 'equipment',
    nativeWidth: 48,
    nativeHeight: 16.81,
    ports: [],
    iconRef: 'D5_Distribution_panel.svg',
    source: 'library'
  },
  {
    id: 'energy-meter',
    label: 'Energy Meter',
    labelNl: 'Kilowatuurmeter',
    discipline: 'electrical',
    category: 'equipment',
    nativeWidth: 48,
    nativeHeight: 20.09,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Energy_meter.svg',
    source: 'library'
  },
  {
    id: 'panel-cross-2',
    label: 'Panel Cross 2',
    labelNl: 'Paneel Kruis 2',
    discipline: 'electrical',
    category: 'equipment',
    nativeWidth: 48,
    nativeHeight: 16.9,
    ports: [],
    iconRef: 'D5_Panel_cross_2.svg',
    source: 'library'
  },
  {
    id: 'panel-cross-empty',
    label: 'Panel Cross Empty',
    labelNl: 'Paneel Kruis Leeg',
    discipline: 'electrical',
    category: 'equipment',
    nativeWidth: 48,
    nativeHeight: 16.9,
    ports: [],
    iconRef: 'D5_Panel_cross_empty.svg',
    source: 'library'
  },
  {
    id: 'panel-cross',
    label: 'Panel Cross',
    labelNl: 'Paneel Kruis',
    discipline: 'electrical',
    category: 'equipment',
    nativeWidth: 48,
    nativeHeight: 16.9,
    ports: [],
    iconRef: 'D5_Panel_cross.svg',
    source: 'library'
  },
  {
    id: 'panel-empty',
    label: 'Panel Empty',
    labelNl: 'Paneel Leeg',
    discipline: 'electrical',
    category: 'equipment',
    nativeWidth: 48,
    nativeHeight: 16.9,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Panel_empty.svg',
    source: 'library'
  },
  {
    id: 'panel-half',
    label: 'Panel Half',
    labelNl: 'Paneel Half',
    discipline: 'electrical',
    category: 'equipment',
    nativeWidth: 48,
    nativeHeight: 16.9,
    ports: [],
    iconRef: 'D5_Panel_half.svg',
    source: 'library'
  },
  {
    id: 'pump-dual-speed-hvac',
    label: 'Pump Dual Speed',
    labelNl: 'Pomp Tweevoudig Toerental',
    discipline: 'heatingAndCooling',
    category: 'equipment',
    nativeWidth: 48,
    nativeHeight: 48,
    ports: [],
    iconRef: 'D5_Pump_dual_speed.svg',
    source: 'library'
  },
  {
    id: 'pump-dual-speed-plumbing',
    label: 'Pump Dual Speed',
    labelNl: 'Pomp Tweevoudig Toerental',
    discipline: 'plumbing',
    category: 'equipment',
    nativeWidth: 48,
    nativeHeight: 48,
    ports: [],
    iconRef: 'D5_Pump_dual_speed.svg',
    source: 'library'
  },
  {
    id: 'pump-speed-controlled-hvac',
    label: 'Pump Speed Controlled',
    labelNl: 'Pomp Toerengeregeld',
    discipline: 'heatingAndCooling',
    category: 'equipment',
    nativeWidth: 47.49,
    nativeHeight: 48,
    ports: [],
    iconRef: 'D5_Pump_speed_controlled.svg',
    source: 'library'
  },
  {
    id: 'pump-speed-controlled-plumbing',
    label: 'Pump Speed Controlled',
    labelNl: 'Pomp Toerengeregeld',
    discipline: 'plumbing',
    category: 'equipment',
    nativeWidth: 47.49,
    nativeHeight: 48,
    ports: [],
    iconRef: 'D5_Pump_speed_controlled.svg',
    source: 'library'
  },
  {
    id: 'pump-hvac',
    label: 'Pump',
    labelNl: 'Pomp',
    discipline: 'heatingAndCooling',
    category: 'equipment',
    nativeWidth: 48,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Pump.svg',
    source: 'library'
  },
  {
    id: 'pump-plumbing',
    label: 'Pump',
    labelNl: 'Pomp',
    discipline: 'plumbing',
    category: 'equipment',
    nativeWidth: 48,
    nativeHeight: 48,
    ports: [
      {
        id: '00000000-0000-0000-0000-000000000001',
        name: 'Center',
        fractionX: 0.5,
        fractionY: 0.5
      }
    ],
    iconRef: 'D5_Pump.svg',
    source: 'library'
  },
  {
    id: 'data-cabinet',
    label: 'Data Cabinet',
    labelNl: 'Patchkast',
    discipline: 'electrical',
    category: 'equipment',
    nativeWidth: 48,
    nativeHeight: 33.57,
    ports: [],
    iconRef: 'D6_Data_cabinet.svg',
    source: 'library'
  }
];
